// Base URL for your live FastAPI chatbot
const API_BASE = "https://stravella-fastapi.onrender.com";

/**
 * Widget Config v1
 * - Source of truth (preferred): window.StravellaWidgetConfig
 * - Optional fallback: <script ... data-client-id="..." data-pack-id="..." ...></script>
 * - Hard fallbacks keep the widget usable even if config is missing.
 */
function stravellaGetEmbeddingScriptEl() {
  const cs = document.currentScript;
  if (cs) return cs;

  // Fallback: try to find the last script that looks like the widget
  const scripts = Array.from(document.getElementsByTagName("script"));
  const match = scripts
    .slice()
    .reverse()
    .find((s) => (s.src || "").toLowerCase().includes("widget"));
  return match || null;
}

function stravellaReadConfigFromDataAttrs(scriptEl) {
  if (!scriptEl) return {};
  const d = scriptEl.dataset || {};
  return {
    client_id: d.clientId || "",
    pack_id: d.packId || "",
    business_name: d.businessName || "",
    greeting_message: d.greetingMessage || "",
    display_phone: d.displayPhone || "",
    service_area_text: d.serviceAreaText || "",
    system_error_message: d.systemErrorMessage || ""
  };
}

function stravellaNormalizeConfig(raw) {
  const defaults = {
    client_id: "unknown-client",
    pack_id: "default-pack",
    business_name: "Stravella",
    greeting_message:
      "Hi! I can help you check availability, book an appointment, reschedule, or cancel — right here in chat.",
    display_phone: "",
    service_area_text: "",
    system_error_message:
      "Sorry — I’m having trouble connecting right now. Please use the phone number on this page to book.",
    // Fixed v1 set (buttons only prefill text; no logic)
    quick_actions: [
      { id: "check_availability", label: "Check availability", prefill: "Check availability" },
      { id: "book", label: "Book appointment", prefill: "Book an appointment" },
      { id: "reschedule", label: "Reschedule", prefill: "Reschedule my appointment" },
      { id: "cancel", label: "Cancel", prefill: "Cancel my appointment" }
    ]
  };

  const cfg = { ...defaults, ...(raw || {}) };

  // Enforce fixed v1 quick actions
  cfg.quick_actions = defaults.quick_actions;

  // Coerce to strings + trim
  cfg.client_id = String(cfg.client_id || "").trim() || defaults.client_id;
  cfg.pack_id = String(cfg.pack_id || "").trim() || defaults.pack_id;
  cfg.business_name = String(cfg.business_name || "").trim() || defaults.business_name;
  cfg.greeting_message = String(cfg.greeting_message || "").trim() || defaults.greeting_message;
  cfg.display_phone = String(cfg.display_phone || "").trim();
  cfg.service_area_text = String(cfg.service_area_text || "").trim();
  cfg.system_error_message =
    String(cfg.system_error_message || "").trim() || defaults.system_error_message;

  return cfg;
}

function stravellaLoadWidgetConfig() {
  const scriptEl = stravellaGetEmbeddingScriptEl();

  const fromWindow =
    typeof window !== "undefined" && window.StravellaWidgetConfig
      ? window.StravellaWidgetConfig
      : null;

  const fromAttrs = stravellaReadConfigFromDataAttrs(scriptEl);

  // Precedence: window config overrides data attributes
  const merged = { ...(fromAttrs || {}), ...(fromWindow || {}) };

  const cfg = stravellaNormalizeConfig(merged);

  // Soft warnings only (never break widget)
  const required = [
    "client_id",
    "pack_id",
    "business_name",
    "greeting_message",
    "system_error_message"
  ];
  const missing = required.filter((k) => !String(cfg[k] || "").trim());
  if (missing.length) {
    console.warn("[StravellaWidget] Missing config keys:", missing);
  }

  return cfg;
}

/**
 * thread_id persistence (Widget v1)
 * - Generated by widget
 * - Stored in localStorage
 * - Sent with every /os/chat request
 */
function stravellaUuid() {
  if (typeof crypto !== "undefined" && crypto.randomUUID) return crypto.randomUUID();

  // RFC4122-ish fallback
  const s4 = () => Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  return `${s4()}${s4()}-${s4()}-${s4()}-${s4()}-${s4()}${s4()}${s4()}`;
}

function stravellaThreadStorageKey(cfg) {
  return `stravella_thread_id::${cfg.client_id}::${cfg.pack_id}`;
}

function stravellaGetOrCreateThreadId(cfg) {
  const key = stravellaThreadStorageKey(cfg);
  try {
    const existing = localStorage.getItem(key);
    if (existing && existing.trim()) return existing.trim();

    const tid = stravellaUuid();
    localStorage.setItem(key, tid);
    return tid;
  } catch (e) {
    // If localStorage is blocked, still function (non-persistent)
    return stravellaUuid();
  }
}

// Load config + thread id once, at init
const WIDGET_CFG = stravellaLoadWidgetConfig();
const THREAD_ID = stravellaGetOrCreateThreadId(WIDGET_CFG);

// Grab elements
const chatButton = document.getElementById("chat-button");
const chatWidget = document.getElementById("chat-widget");
const closeWidgetBtn = document.getElementById("close-widget");
const chatHeaderTitle = document.getElementById("chat-header-title");
const trustBlock = document.getElementById("chat-trust");
const trustPhone = document.getElementById("chat-trust-phone");
const trustArea = document.getElementById("chat-trust-area");
const quickActions = document.getElementById("quick-actions");
const chatBody = document.getElementById("chat-body");
const chatInput = document.getElementById("chat-input");
const sendBtn = document.getElementById("send-btn");

// Apply config to UI (presentation only)
function applyConfigToUI() {
  if (chatHeaderTitle) chatHeaderTitle.textContent = WIDGET_CFG.business_name;

  // Trust block always visible (passive trust)
  if (trustBlock) {
    const hasPhone = Boolean(WIDGET_CFG.display_phone);
    const hasArea = Boolean(WIDGET_CFG.service_area_text);

    // If neither provided, hide the block so we don’t show empty chrome
    if (!hasPhone && !hasArea) {
      trustBlock.style.display = "none";
    } else {
      trustBlock.style.display = "block";
      if (trustPhone) trustPhone.textContent = WIDGET_CFG.display_phone || "";
      if (trustArea) trustArea.textContent = WIDGET_CFG.service_area_text || "";
    }
  }

  // Quick actions (prefill only)
  if (quickActions) {
    quickActions.innerHTML = "";
    WIDGET_CFG.quick_actions.forEach((a) => {
      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = "stravella-quick-action-btn";
      btn.textContent = a.label;
      btn.addEventListener("click", () => {
        chatInput.value = a.prefill;
        chatInput.focus();
      });
      quickActions.appendChild(btn);
    });
  }
}

applyConfigToUI();

// Show widget when button clicked
chatButton.addEventListener("click", () => {
  chatWidget.style.display = "flex";
  chatButton.style.display = "none";
  chatInput.focus();

  // Send greeting (first open only)
  if (!chatBody.dataset.hasGreeted) {
    addBotMessage(WIDGET_CFG.greeting_message);
    chatBody.dataset.hasGreeted = "true";
  }
});

// Hide widget and show button again
closeWidgetBtn.addEventListener("click", () => {
  chatWidget.style.display = "none";
  chatButton.style.display = "flex";
});

// Send message on button click
sendBtn.addEventListener("click", () => {
  handleSend();
});

// Send on Enter key
chatInput.addEventListener("keydown", (event) => {
  if (event.key === "Enter" && !event.shiftKey) {
    event.preventDefault();
    handleSend();
  }
});

// Core send logic
async function handleSend() {
  const text = chatInput.value.trim();
  if (!text) return;

  addUserMessage(text);
  chatInput.value = "";
  chatInput.focus();

  // Disable send while waiting
  sendBtn.disabled = true;

  try {
    const reply = await sendMessageToBot(text);
    addBotMessage(
      reply || "I’m here and listening, but something went a bit quiet. Try asking again?"
    );
  } catch (err) {
    console.error("Chat error:", err);
    addBotMessage(WIDGET_CFG.system_error_message);
  } finally {
    sendBtn.disabled = false;
  }
}

// Call your FastAPI /os/chat endpoint (StravellaOS agent pipeline)
// NOTE: The widget does NOT choose outcomes; backend text remains source of truth.
async function sendMessageToBot(message) {
  const response = await fetch(`${API_BASE}/os/chat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      message,
      thread_id: THREAD_ID,
      client_id: WIDGET_CFG.client_id,
      pack_id: WIDGET_CFG.pack_id,
      channel: "chat"
    })
  });

  if (!response.ok) {
    throw new Error(`HTTP error: ${response.status}`);
  }

  const data = await response.json();
  return data.reply;
}

// Helpers to render messages
function addUserMessage(text) {
  const bubble = document.createElement("div");
  bubble.classList.add("message", "user");
  bubble.textContent = text;
  chatBody.appendChild(bubble);
  scrollChatToBottom();
}

function addBotMessage(text) {
  const bubble = document.createElement("div");
  bubble.classList.add("message", "bot");
  bubble.textContent = text;
  chatBody.appendChild(bubble);
  scrollChatToBottom();
}

function scrollChatToBottom() {
  chatBody.scrollTop = chatBody.scrollHeight;
}
